python run_squad.py \
    --model_type=bert \
    --model_name_or_path=cl-tohoku/bert-base-japanese-whole-word-masking \
    --do_train \
    --do_eval \
    --train_file=DDQA-1.0/DDQA-1.0_RC-QA_train.json \
    --predict_file=DDQA-1.0/DDQA-1.0_RC-QA_dev.json \
    --learning_rate 3e-5 \
    --num_train_epochs 2 \
    --max_seq_length 384 \
    --doc_stride 128 \
    --overwrite_output_dir \
    --output_dir output/ \
    --per_gpu_train_batch_size 1 \
    --no_cuda